# Generated by Django 3.1.4 on 2020-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_corp', models.CharField(db_index=True, max_length=50)),
                ('name_in_corp_sys', models.CharField(default='None', max_length=250, unique=True)),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
