# Generated by Django 3.1.4 on 2020-12-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsAndAnalitics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='name_in_corp_sys',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
